information_extractor_task:
  description: >
    Engage with a customer to gather all the details for their errand request.
    The customer's initial request is: '{customer_request}'.
    Ask clarifying questions until you have all the required pieces of information.
    Be friendly and professional throughout the conversation.
  expected_output: >
    A complete list of all the gathered information:
    - Item Description: [Details]
    - Pickup Address: [Details]
    - Delivery Address: [Details]
    - Pickup Contact Name: [Details]
    - Pickup Contact Phone: [Details]
    - Recipient Name: [Details]
    - Recipient Phone: [Details]
    - Budget: [Details]
  agent: information_extractor

task_verify_and_brief:
  description: >
    Review the information collected from the customer.
    Ensure that every required field is present and looks complete.
    If any information is missing, you would normally send it back, but for now, assume it's complete.
    Format the verified details into a structured 'Errand Brief
  expected_output: >
    A final, structured 'Errand Brief' ready for dispatch.
    The brief should be formatted clearly like this:

    **New Errand Request**
    -------------------------
    **Item:** [Item Description]
    **Pickup From:** [Pickup Address]
    **Deliver To:** [Delivery Address]
    **Client Contact:** [Pickup Contact Name] at [Pickup Contact Phone]
    **Recipient Contact:** [Recipient Name] at [Recipient Phone]
    **Budget:** [Budget]
    -------------------------
    **Status:** Verified. Ready for runner dispatch.""",
  agent: errand_manager
  context: [information_extractor_task] 
 
  

